name: Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build
        run: GOOS=linux GOARCH=arm GOARM=6 make build
      - uses: actions/upload-artifact@v2
        with:
          name: build-arm6-${{ github.sha }}
          path: dist/
